version: "3.7"

services:
  kish-insurance-service:
    image: ${DOCKER_REGISTRY-}kishinsuranceservice
    build:
      context: kish-insurence-services
      dockerfile: Dockerfile
    networks:
      - db
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    hostname: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Mehran@SQRootPass
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - db
  redis:
    container_name: redis-insurence
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db
volumes:
  sqldb:
  sqlserver_data:
networks:
  db:
    driver: bridge
