name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Build and Run Tests
        run: |
          # Build the test project
          docker-compose -f docker-compose.yml exec -T kish-insurance-service dotnet build /app/kish-insurance-service.Tests/kish-insurance-service.Tests.csproj --no-restore

          # Run the tests
          docker-compose -f docker-compose.yml exec -T kish-insurance-service dotnet test /app/kish-insurance-service.Tests/kish-insurance-service.Tests.csproj --no-restore --verbosity normal

      - name: Push Docker image to DockerHub
        run: |
          docker tag kishinsuranceservice ${{ secrets.DOCKER_USERNAME }}/kishinsuranceservice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/kishinsuranceservice:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
